# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 2.0.0"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Name of Vagrant Box to use as base
  config.vm.box = "hashicorp/bionic64"
  
  # Don't generate new SSH key, but use the default insecure key
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|

    # Name to display in Virtualbox
    vb.name = "AcnTech ML-Developer Jenkins"

    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize CPU count
    vb.cpus = "2"

    # Customize the amount of memory on the VM
    vb.memory = "4096"

    # Customize amount of video memory
    vb.customize ["modifyvm", :id, "--vram", "128"]

    # Disable 3D acceleration
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  # Setting ports that can be assigned if preferred ports are taken
  config.vm.usable_port_range = 8000..8999

  #Port forwarding
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", auto_correct: true   # HTTP

  # Install puppet
  config.vm.provision :shell, :inline => 'apt-get -y update; apt-get -y install puppet'
  
  # Enable provisioning with puppet
  config.vm.provision "puppet" do |puppet|
    puppet.environment = "mljenkins"
    puppet.environment_path = "../provision/puppet/environments"
    puppet.module_path = "../provision/puppet/modules"
    puppet.options = "--verbose --debug"
  end
end
